Fix issue where requiresjs-config.js files were not being generated on Magento 2.1.3+
davidalger/capistrano-magento2 pull request #74
Opened 2017-07-13 03:32 UTC by erikhansen

In version 2.1.0 of Magento, it became necessary to run the `bin/magento setup:static-content:deploy` with the `HTTPS=on` in order for secure versions of the requirejs-config.js file to get generated (e.g., `pub/static/_requirejs/frontend/Magento/blank/en_US/secure/requirejs-config.js`). This Magento core bug was worked around in version of 0.5.0 of this Gem (see [this issue](https://github.com/davidalger/capistrano-magento2/issues/21) for context).

In version 2.1.3 of Magento, the behavior of the `bin/magento setup:static-content:deploy` command changed. In versions 2.1.0-2.1.2, you could pass the following flags and the secure versions of requirejs-config.js would get generated:
```
export HTTPS="on"; bin/magento setup:static-content:deploy --no-javascript --no-ansi en_US --no-css --no-less --no-images --no-fonts --no-html --no-misc --no-html-minify
```

However starting in version 2.1.3, if you passed the `--no-javascript` flag, the secure versions of the requirejs-config.js would never get generated.

This pull requests checks the current version of Magento, and only if the version is between 2.1.0 and 2.1.2 will the `--no-javascript` flag get added.

Let me know if you want to see verification of the behavior difference between 2.1.2 and 2.1.3, although I'm confident of this being the version that the behavior changed as I had an existing 2.1.2 install and installed a vanilla 2.1.3 install just to test this.

2017-07-13 16:14 UTC, davidalger requested changes
@erikhansen Please address the one issue I noted in code-comments. Thanks!

2017-07-13 16:14 UTC, davidalger commented on lib/capistrano/tasks/magento.rake
> +          if _magento_version <= Gem::Version.new('2.1.3')
This is incorrectly using the <= operator. As it is, the flag will still be used on version 2.1.3. Can you fix this?

2017-07-13 16:25 UTC, erikhansen commented
@davidalger Good catch. I made the requested change.

2017-07-23 03:40 UTC, merged

2017-07-23 03:41 UTC, davidalger commented
Thanks for the PR. This will be included in the next tagged release.